{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "coredns-k3s.namespace" . }}
  annotations:
    prometheus.io/port: "{{ .Values.service.metricsPort }}"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: {{ .Values.clusterDNS }}
  clusterIPs:
{{ toYaml .Values.clusterDNSList | indent 4 }}
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      protocol: TCP
{{- end }}
